version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202104-01
      
    steps:
      - checkout  # Checkout code from repository
      - run:
          name: Install dependencies
          command: make deps  # Zainstaluj zależności
      - run:
          name: Run tests
          command: make test  # Uruchom testy

workflows:
  basic:
    jobs:
      - build-and-test