version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
        name: Install dependencies
        command: |
          pip install -r requirements.txt
      - run:
        name: Build Docker image
        command: make docker_build
      - run:
        name: Push Docker image
        command: make docker_push

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
